name: Main Production Workflow

on:
  push:
    branches:
      - main  # main 브랜치에 커밋될 때 실행

jobs:
  test-and-deploy:
    name: Test and Deploy to Production
    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v4

    # # 2. 커밋 메시지 출력
    # - name: Display Commit Message
    #   run: echo "Commit Message: ${{ github.event.head_commit.message }}"

    # 3. Node.js 설치
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'  # Node.js 버전

    # 4. 의존성 설치
    - name: Install dependencies
      run: npm install

    # # 5. 테스트 실행
    # - name: Run tests
    #   run: npm test -- --watchAll=false  # 모든 테스트 실행

    # 6. 빌드 실행
    - name: Build project
      run: npm run deploy  # 프로덕션 빌드 실행

    # 7. 프로덕션 환경 배포
    - name: Deploy to GitHub Pages (Production)
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # 빌드 결과물을 프로덕션 환경에 배포
